steps:
    # Build container image
  - name: docker
    id: Build container image
    entrypoint: sh
    args:
      - -c
      - |
        docker build \
        -t ${_SERVICE_NAME}:latest .

    # Tag image and push the container image to the Artifact Registry
  - name: docker
    waitFor:
      - Build container image
    id: Tag image and push
    entrypoint: sh
    args:
      - -c
      - |
        echo latest
        docker tag ${_SERVICE_NAME} ${_IMAGE}:latest
        docker push --all-tags ${_IMAGE}

    # Deploy container image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy to Cloud Run
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE_NAME} \
        --image=${_IMAGE}:$(cat /workspace/_VERSION) \
        --revision-suffix=$(cat /workspace/_VERSION) \
        --region=${_REGION} \
        --platform=managed \
        --max-instances=${_MAX_INSTANCES} \
        --cpu=${_CPU} \
        --memory=${_MEMORY}Mi \
        --timeout=${_TIMEOUT} \
        --concurrency=${_CONCURRENCY} 

timeout: 600s
images:
  - ${_IMAGE}:latest

options:
  dynamic_substitutions: true # Allow creation of substitution with another substitution
substitutions:
  _CONCURRENCY: "10"
  _CPU: "1"
  _IMAGE: "gcr.io/flowing-subset-365919/github.com/kseetal/project"
  _MAX_INSTANCES: "5"
  _MEMORY: "256"
  _TIMEOUT: "300"
  _REGION: "eu-west1"
  _SERVICE_NAME: "cameraapp"
  _ARTIFACT_REPOSITORY: "camera-artifact"
